import MainCategory from "@/conponents/main/mainCategory/MainCategory";
import MainHero from "@/conponents/main/mainHero/MainHero";
import Head from "next/head";
import { FC } from "react";

interface Category {
	_id: string;
	lang: string;
	popular: boolean;
	title: string;
	viewCount: number;
}

interface HomeProps {
	data: Category[];
}

const Home: FC<HomeProps> = ({ data }) => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main style={{ height: "200vh" }}>
				<MainHero />
				<MainCategory categories={data} />
			</main>
		</>
	);
};

export async function getServerSideProps() {
	// Получите данные из вашего источника (API, базы данных и т.д.)
	const response = await fetch("https://api.puputravel.com/api/categories");
	const data: Category[] = await response.json();

	return {
		props: {
			data, // Передаем данные компоненту как свойство
		},
	};
}

export default Home;
